### ISSUE TITLE
Make a calculator

### ISSUE THREAD

**Issue by theritiktiwari** [codingwalls/hacktober-2022#3]

**Comment by sangalgovind** [comment]
@theritiktiwari pls accept my PR

**Comment by theritiktiwari** [comment]
GUI of calculator is need, people can use it through web page.

**Comment by Yashmittal01** [comment]
please assign it to me

**Comment by Arika008** [comment]
Hey @theritiktiwari  please go through my PR #7 and merge it

**Comment by ShreyaShukla03** [comment]
Please check and merge PR #11
