### ISSUE TITLE
Make a clock by JavaScript

### ISSUE THREAD

**Issue by theritiktiwari** [codingwalls/hacktober-2022#9]

**Comment by Abhishek-Vaidya** [comment]
I can solve this issue can you assign me this issue?

**Comment by ShreyaShukla03** [comment]
Please check PR #10 and plaese merge it if found useful.

**Comment by Sunnygupta00** [comment]
hii can i contribute to this repo,  please assign me

**Comment by Yashmittal01** [comment]
please assign it to me
